README.md

This PR resolves https://github.com/andrewnguonly/Lumos/issues/11.

Update `README` to include instructions for pulling `llama2` model and changing models

---

README.md

This PR resolves https://github.com/andrewnguonly/Lumos/issues/13.

Update README with instructions to run Ollama API from Docker container

---

src/components/ChatBar.tsx
src/contentConfig.ts
src/scripts/background.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/17.

Implement custom chunking configs

---

src/components/ChatBar.tsx
src/scripts/background.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/22.

Implement response streaming

---

webpack.config.js

This PR resolves https://github.com/andrewnguonly/Lumos/issues/29

Remove web-llm config from webpack config

---

src/components/ChatBar.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/30

Focus text field after token streaming is complete

---

docs/firefox.md

This PR resolves https://github.com/andrewnguonly/Lumos/issues/36

Create docs page for Firefox install

---

README.md
src/components/ChatBar.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/40

Add functionality to pass highlighted content to RAG workflow

---

package-lock.json
package.json
src/scripts/background.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/54

Update LangChain package and imports

---

README.md
manifest.json
package-lock.json
package.json
src/components/ChatBar.tsx
src/pages/Options.css
src/pages/Options.tsx
src/scripts/background.ts

1. https://github.com/andrewnguonly/Lumos/issues/42
1. https://github.com/andrewnguonly/Lumos/issues/54

PR for version `1.0.3`

---

README.md
src/components/ChatBar.tsx
src/scripts/background.ts
src/themes/AppTheme.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/60.

Add feature to manually disable content parsing

---

README.md
src/pages/Options.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/66.

Validate Vector Store TTL (minutes) config

---

src/components/ChatBar.css

This PR resolves https://github.com/andrewnguonly/Lumos/issues/31.

Set max width of `@chatscope` `Avatar` component`

---

.github/workflows/ci.yml
README.md

This PR resolves https://github.com/andrewnguonly/Lumos/issues/48.

Add CI workflow configuration to run `eslint`

---

src/components/ChatBar.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/81.

Add listener for `cmd+k` to clear messages

---

src/components/ChatBar.tsx
src/pages/Options.tsx
src/scripts/background.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/80.

Skip script injection for chrome URLs

---

README.md
__tests__/contentConfig.test.ts
src/components/ChatBar.tsx
src/contentConfig.ts

This resolves PR https://github.com/andrewnguonly/Lumos/issues/18.
This change is backward compatible with existing configuration.

Support custom content config for URL paths

---

src/scripts/background.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/84.

Refactor prompt classification functions into a single function

---

src/components/ChatBar.tsx
src/scripts/background.ts
src/tools/calculator.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/50.

Persist req/res state when popup is closed

---

src/components/ChatBar.tsx
src/pages/Options.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/96.
`Options` page:

Display error when app is unable to connect to Ollama host

---

src/components/ChatBar.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/102.

Add more shortcuts

---

src/components/ChatBar.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/108.

Change input field to multi-line input

---

package-lock.json
package.json
src/components/ChatBar.tsx
src/components/CodeBlock.tsx

This resolves PR https://github.com/andrewnguonly/Lumos/issues/107.

Add support for rendering markdown and syntax highlighting

---

README.md
package-lock.json
package.json
src/components/ChatBar.tsx
src/scripts/background.ts
src/scripts/content.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/90.

Add messaging to state when cache is skipped and update documentation

---

README.md
src/pages/Options.css
src/pages/Options.tsx
src/scripts/background.ts
src/themes/AppTheme.tsx
src/tools/calculator.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/98.

Add ability to enable/disable tools

---

src/pages/Options.css
src/pages/Options.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/118.

Reduce width of options page

---

README.md
docs/edge.md
docs/linux.md

This PR resolves https://github.com/andrewnguonly/Lumos/issues/116 and https://github.com/andrewnguonly/Lumos/issues/117.

Add docs for installing on Edge

---

README.md
src/pages/Options.tsx
src/scripts/background.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/77.

Add functionality to select custom embedding model

---

src/components/ChatBar.tsx
src/pages/Options.tsx
src/scripts/background.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/122.

Add chat history to prompt

---

__tests__/contexts/ThemeContext.test.tsx
src/components/ChatBar.tsx
src/pages/Options.tsx
src/themes/AppTheme.tsx
tsconfig.json

1. Move test file under `__tests__`.
1. Change primary color to light green.

Adjust dark mode palette

---

.eslintrc
package-lock.json
package.json
src/components/ChatBar.tsx
src/components/ChatHistory.tsx
src/contexts/ThemeContext.tsx
src/index.tsx
src/options.tsx
src/pages/Options.tsx
src/scripts/background.ts
src/themes/AppTheme.tsx
src/vectorstores/enhanced_memory.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/134.

Reorder imports

---

README.md
package-lock.json
package.json
src/components/ChatBar.tsx
src/document_loaders/csv.ts
src/document_loaders/dynamic_file.ts
src/document_loaders/util.ts
src/scripts/background.ts
webpack.config.js

This PR resolves https://github.com/andrewnguonly/Lumos/issues/131.

Add support for uploading PDFs

---

README.md
src/components/ChatBar.tsx
src/document_loaders/dynamic_file.ts
src/document_loaders/util.ts
src/scripts/background.ts

This PR resolves https://github.com/andrewnguonly/Lumos/issues/147.

Support uploading image file attachment

---

README.md
src/components/ChatBar.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/150.

Add shortcut to remove attachment

---

src/components/ChatBar.css
src/components/ChatBar.tsx
src/pages/Options.css
src/pages/Options.tsx
src/pages/Popup.css
src/pages/Popup.tsx

This PR might resolve https://github.com/andrewnguonly/Lumos/issues/159.

Rename CSS classes

---

src/components/ChatBar.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/162.

Change message preview to first AI message

---

src/pages/Options.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/166.

Add `snowflake-arctic-embed` to embeddings model list

---

src/pages/Options.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/169.

Add new multimodal models

---

__tests__/contentConfig.test.ts
src/contentConfig.ts

Fixes https://github.com/andrewnguonly/Lumos/issues/185

Fix bug for matching subdomains

---

README.md
src/components/ChatBar.tsx

This PR resolves https://github.com/andrewnguonly/Lumos/issues/188.

Check alt key for shortcuts.
